// Mystery pictures for the color-by-answer pages. Each picture is a square of
// letters; each letter is a crayon from CRAYONS. Kids solve the problem in each
// square and color it with the crayon for that answer — the picture appears.

export const CRAYONS = {
  '.': { name: 'white', hex: '#ffffff' },
  r: { name: 'red', hex: '#f03e3e' },
  o: { name: 'orange', hex: '#fd7e14' },
  y: { name: 'yellow', hex: '#ffd43b' },
  g: { name: 'light green', hex: '#8ce99a' },
  G: { name: 'dark green', hex: '#2b8a3e' },
  s: { name: 'light blue', hex: '#74c0fc' },
  b: { name: 'blue', hex: '#1c7ed6' },
  p: { name: 'purple', hex: '#9c6ade' },
  k: { name: 'pink', hex: '#f9a8d4' },
  m: { name: 'dark pink', hex: '#c2255c' },
  n: { name: 'brown', hex: '#8d5524' },
  a: { name: 'gray', hex: '#868e96' },
}

export const PICTURES = [
  {
    id: 'heart',
    title: 'a heart',
    hint: 'Something you give with love',
    rows: [
      'kkkkkkkkkk',
      'krrkkkkrrk',
      'rr.rkkrrrr',
      'r.rrrrrrrr',
      'rrrrrrrrrr',
      'krrrrrrrrk',
      'kkrrrrrrkk',
      'kkkrrrrkkk',
      'kkkkrrkkkk',
      'kkkkkkkkkk',
    ],
  },
  {
    id: 'smiley',
    title: 'a smiley face',
    hint: 'It is always happy',
    rows: [
      '...yyyy...',
      '.yyyyyyyy.',
      '.yyyyyyyy.',
      'yyybyybyyy',
      'yyybyybyyy',
      'yyyyyyyyyy',
      'yryyyyyyry',
      '.yrrrrrry.',
      '.yyyyyyyy.',
      '...yyyy...',
    ],
  },
  {
    id: 'apple',
    title: 'an apple',
    hint: 'A crunchy snack',
    rows: [
      'sssssnssss',
      'sssssnGGss',
      'ssrrrnrrss',
      'srrrrrrrrs',
      'rr.rrrrrrr',
      'r.rrrrrrrr',
      'rrrrrrrrrr',
      'srrrrrrrrs',
      'srrrrrrrrs',
      'ssrrssrrss',
    ],
  },
  {
    id: 'house',
    title: 'a house',
    hint: 'Somebody lives here',
    rows: [
      'ssssrrssss',
      'sssrrrrsss',
      'ssrrrrrrss',
      'srrrrrrrrs',
      'syyyyyyyys',
      'sy..yyyyys',
      'sy..yynnys',
      'syyyyynnys',
      'gggggggggg',
      'gggggggggg',
    ],
  },
  {
    id: 'tree',
    title: 'an apple tree',
    hint: 'Birds nest in it, and it grows a snack',
    rows: [
      'sssGGGGsss',
      'ssGGrGGGss',
      'sGGGGGGrGs',
      'sGrGGGGGGs',
      'sGGGGrGGGs',
      'ssGGGGGGss',
      'ssssnnssss',
      'ssssnnssss',
      'sssnnnnsss',
      'GGGGGGGGGG',
    ],
  },
  {
    id: 'star',
    title: 'a star',
    hint: 'It twinkles at night',
    rows: [
      'bbbbyybbbb',
      'bbbbyybbbb',
      'bbbyyyybbb',
      'yyyyyyyyyy',
      'byyyyyyyyb',
      'bbyyyyyybb',
      'bbyyyyyybb',
      'byyybbyyyb',
      'byybbbbyyb',
      'bybbbbbbyb',
    ],
  },
  {
    id: 'ice-cream',
    title: 'an ice cream cone',
    hint: 'A cold treat',
    rows: [
      '....rr....',
      '...kkkk...',
      '..kkkkkk..',
      '.kkkkkkkk.',
      '.kkkkkkkk.',
      '..yyyyyy..',
      '..yyyyyy..',
      '...yyyy...',
      '....yy....',
      '....yy....',
    ],
  },
  {
    id: 'sailboat',
    title: 'a sailboat',
    hint: 'The wind makes it go',
    rows: [
      '....nrr...',
      '....ny....',
      '....nyy...',
      '....nyyy..',
      '....nyyyy.',
      '....nyyyyy',
      '.rrrrrrrr.',
      '..rrrrrr..',
      'bbbbbbbbbb',
      'bbbbbbbbbb',
    ],
  },
  {
    id: 'mushroom',
    title: 'a mushroom',
    hint: 'It grows in the forest',
    rows: [
      'sssrrrrsss',
      'ssrr.rrrss',
      'srrrrrr.rs',
      'sr.rrrrrrs',
      'rrrrr.rrrr',
      'rrrrrrrrrr',
      'sss....sss',
      'sss....sss',
      'ss......ss',
      'gggggggggg',
    ],
  },
  {
    id: 'pig',
    title: 'a pig',
    hint: 'It says oink',
    rows: [
      'kk......kk',
      'kkkkkkkkkk',
      '.kkkkkkkk.',
      '.kbkkkkbk.',
      '.kkkkkkkk.',
      '.kkmmmmkk.',
      '.kknmmnkk.',
      '.kkmmmmkk.',
      '..kkkkkk..',
      '..........',
    ],
  },
  {
    id: 'rocket',
    title: 'a rocket',
    hint: 'It zooms into space',
    rows: [
      'bbbbbbrrbbbbyb',
      'bbbbbrrrrbbbbb',
      'bybbbaaaabbbbb',
      'bbbbaaaaaabbbb',
      'bbbbaayyaabbyb',
      'bbbbaayyaabbbb',
      'bbbbaaaaaabbbb',
      'bbbbaaaaaabbbb',
      'bbbraaaaaarbbb',
      'bbrraaaaaarrbb',
      'bbrrbaaaabrrbb',
      'bbbbbrrrrbbbbb',
      'bbbbbbyybbbbbb',
      'bybbbbbbbbbbyb',
    ],
  },
  {
    id: 'butterfly',
    title: 'a butterfly',
    hint: 'It used to be a caterpillar',
    rows: [
      'ggggnggggngggg',
      'gggggnggnggggg',
      'gppppgnngppppg',
      'ppyyppnnppyypp',
      'pyyyppnnppyyyp',
      'pyyyppnnppyyyp',
      'ppppppnnpppppp',
      'gkkkkknnkkkkkg',
      'kkookknnkkookk',
      'kkookknnkkookk',
      'gkkkkknnkkkkkg',
      'ggkkkgnngkkkgg',
      'ggggggnngggggg',
      'gggggggggggggg',
    ],
  },
  {
    id: 'cat',
    title: 'a cat',
    hint: 'It says meow',
    rows: [
      '.o..........o.',
      '.oo........oo.',
      '.ooo......ooo.',
      '.oooooooooooo.',
      'oooooooooooooo',
      'oooggooooggooo',
      'ooogboooobgooo',
      'ooooookkoooooo',
      'bboooonnoooobb',
      'oooonoooonoooo',
      'bbooonnnnooobb',
      '.oooooooooooo.',
      '..oooooooooo..',
      '....oooooo....',
    ],
  },
]
